import ExcelJS from "exceljs";
import type { TestSuite } from "@/lib/schemas/test-case";
import type { ValidationReport } from "@/lib/schemas/validation";
import {
  applyBorders,
  autoFitColumns,
  formatSteps,
  formatTestData,
  setCell,
  setHeaderCell,
} from "./excel-helpers";

/**
 * Horizontal ISTQB-standard sheet — the format most enterprise QA teams and
 * test-management tools expect. One row per test case.
 */

const COLUMNS = [
  "Test Case ID",
  "Title",
  "Requirement",
  "Precondition",
  "Test Steps",
  "Test Data",
  "Expected Result",
  "Priority",
  "Type",
  "Technique",
  "Validation",
] as const;

export async function exportIstqbExcel(suite: TestSuite, validation?: ValidationReport): Promise<Buffer> {
  const wb = new ExcelJS.Workbook();
  wb.creator = "TestcaseForge";
  const ws = wb.addWorksheet("Test Cases");

  // Title block
  setHeaderCell(ws, 1, 1, "Function Code");
  setCell(ws, 1, 2, suite.functionCode);
  setHeaderCell(ws, 1, 3, "Function Name");
  setCell(ws, 1, 4, suite.functionName);
  setHeaderCell(ws, 2, 1, "Requirement");
  setCell(ws, 2, 2, `${suite.requirement.id}: ${suite.requirement.title}`);
  setHeaderCell(ws, 2, 3, "Generated By");
  setCell(ws, 2, 4, `${suite.meta.providerId}/${suite.meta.modelId} @ ${suite.meta.generatedAt}`);

  const headerRow = 4;
  COLUMNS.forEach((label, i) => setHeaderCell(ws, headerRow, i + 1, label));

  const statusById = new Map(validation?.perCase.map((c) => [c.testCaseId, c]) ?? []);

  suite.testCases.forEach((tc, i) => {
    const row = headerRow + 1 + i;
    const v = statusById.get(tc.id);
    const validationText = v
      ? v.status === "valid"
        ? "OK"
        : `${v.status.toUpperCase()}: ${v.issues.map((issue) => issue.ruleId).join(", ")}`
      : "";

    setCell(ws, row, 1, tc.id);
    setCell(ws, row, 2, tc.title);
    setCell(ws, row, 3, tc.requirementRef.requirementId);
    setCell(ws, row, 4, tc.preconditions.join("\n"));
    setCell(ws, row, 5, formatSteps(tc.steps));
    setCell(ws, row, 6, formatTestData(tc.testData));
    setCell(ws, row, 7, tc.expectedResult);
    setCell(ws, row, 8, tc.priority);
    setCell(ws, row, 9, tc.type);
    setCell(ws, row, 10, tc.technique ?? "");
    setCell(ws, row, 11, validationText);

    for (const col of [4, 5, 6, 7]) {
      ws.getCell(row, col).alignment = { wrapText: true, vertical: "top" };
    }
  });

  const lastRow = headerRow + suite.testCases.length;
  applyBorders(ws, lastRow, COLUMNS.length);
  autoFitColumns(ws, { max: 55 });
  ws.getColumn(5).width = 55;
  ws.getColumn(7).width = 50;
  ws.views = [{ state: "frozen", ySplit: headerRow }];

  return Buffer.from(await wb.xlsx.writeBuffer());
}
